### PR TITLE
Top navigation in server selector

### PR DESCRIPTION
**Pull request by SparklesReal**

### CODE REVIEW

**Comment by SparklesReal** [comment]
Oops did something wrong it seems like, just wanted to make one commit with the topnavigation

**Comment by Julian-Louis** [comment]
Hey @SparklesReal 
Thank you for your PR.
Can you rebase it to clean the history ?

**Comment by SparklesReal** [comment]
> Hey @SparklesReal Thank you for your PR. Can you rebase it to clean the history ?

Will try

**Comment by SparklesReal** [comment]
> Hey @SparklesReal Thank you for your PR. Can you rebase it to clean the history ?

I kind of did in #61 but I don't know if I did something wrong, sorry I'm not very used to git/github

**Comment by Julian-Louis** [comment]
I just reverted this PR as the base branch was incorrect (main instead of ui-refactor)

**Pull request merged**
