### PR TITLE
UI Refactor

### PR DESCRIPTION
**Pull request by Julian-Louis**

### CODE REVIEW

**Comment by Julian-Louis** [comment]
**Design that we want to achieve:**
MacBook Pro 14_ - 8
MacBook Pro 14_ - 6
MacBook Pro 14_ - 9
MacBook Pro 14_ - 11

**Comment by SparklesReal** [comment]
Could the dark mode bot icons be added back? To me it looks very off with the light mode bot and search bar in the dark mode.

**Comment by Julian-Louis** [comment]
@SparklesReal the bot icon's dark mode didn't exist yet when made these mockups, that's why icons are light.
But yes, we will keep it

**Comment by SparklesReal** [comment]
Sounds good!

**Comment by Julian-Louis** [comment]
Hey @SparklesReal,
Can I get your opinions/review on the changes on this PR?
What do you think of the new UI?

Do you think I can merge it ?

**Comment by SparklesReal** [comment]
> Hey @SparklesReal,
> Can I get your opinions/review on the changes on this PR?
> What do you think of the new UI?
> 
> Do you think I can merge it ?

It's hard for me to say now that I don't have it infront of me. I think it might needs some touchups and fixes before a merge. One thing that annoyed me is that the searchbox was not centered. I'll look more at it tomorrow and fix some stuff or write down stuff I dislike.

**Comment by Julian-Louis** [comment]
@SparklesReal You can access it through this URL: [ui-refactor.simrail-map.pages.dev](https://ui-refactor.simrail-map.pages.dev/)

**Comment by SparklesReal** [comment]
> Hey @SparklesReal, Can I get your opinions/review on the changes on this PR? What do you think of the new UI?
> 
> Do you think I can merge it ?

In the server browser I found these problems:
On phone it only shows the left part of the background image, I think it would look better if it showed the middle or something a bit more interesting. 
On computer this image could also shift a bit to the right in order to show the entire front of the ED250 train. On my 1440p screen it seems to even show a bit less of the tip than on the 1080p monitor.

The EU3 server could use a EU flag as it looks odd with one server not having a flag.

In the map I found these problems:
The search box not being centered (see image)
image

The text that explains the icons in the bottom left corner could also use some dark mode.

That all my problems for now but you know that you can expect pull requests from me in the future xD
I would fix some of the stuff myself but I have to work on another project for now sadly. But overall I must say that you have done great work.

**Comment by Julian-Louis** [comment]
Thank you for your feedback !
I fixed all the issues except for the EU flag, I think maybe we can merge it, and add the icon later, what do you think ?

**Comment by SparklesReal** [comment]
> Thank you for your feedback !
> I fixed all the issues except for the EU flag, I think maybe we can merge it, and add the icon later, what do you think ?

Sounds good

**Pull request merged**
