### PR TITLE
Signal status in train details

### PR DESCRIPTION
**Pull request by Over441**
I managed to do a little trick for issue #48 (i.e. mine).
Even if it's not what I wanted, it could be interesting to have.

Here's what it looks like:
image

### CODE REVIEW

**Comment by SparklesReal** [comment]
This looks good to me, what is the reason for the draft?

**Comment by Over441** [comment]
Because I was waiting for approval

**Comment by Over441** [comment]
But if all is well, it can be put on, ready for review.

**Comment by SparklesReal** [comment]
Ready for review is a way of waiting for approval. I'm not a skilled github user but I almost always use ready for review from the start if it is not something that is not done / half-done. I think you can put this to ready for review.

**Comment by Over441** [comment]
For the moment, I don't need to merge, I need to make changes to adapt this code to the new one (from the main branch).

**Comment by Over441** [comment]
Closed accidentally

**Comment by Over441** [comment]
Ready to merge

**Comment by Julian-Louis** [comment]
Hello, thank you for your contribution !

I think this feature is a good idea, however I'm not a big fan of the UI implementation.
Centering the signal status (while all other elements are left-aligned) in the card creates an offset with the other elements.
Do you think you can improve this ?

**Comment by Over441** [comment]
Thanks for your comment.

Regarding the UI, yes, I think I can improve that.
If you have an idea of what could be better for the UI, don't hesitate to tell me.
I'll see what I can do on my side.

**Comment by Julian-Louis** [comment]
You can take a look at https://github.com/simrail/map-v2/pull/56
This is likely how the future pages will look, maybe you can take inspiration of that ?
Or maybe we can wait for some refactor to be done, then integrate your feature inside the new UI.
But we still need to edit our mockup according your feature

**Comment by Over441** [comment]
> You can take a look at #56 This is likely how the future pages will look, maybe you can take inspiration of that ? Or maybe we can wait for some refactor to be done, then integrate your feature inside the new UI. But we still need to edit our mockup according your feature

What do you think of this?
 
image

**Comment by Over441** [comment]
So far, I think the UI is pretty good. Unfortunately, I can't reduce the space between _Signal Status_ and _Signal Speed_ too much, otherwise the image would be too small.
Now, if you want to put it in the main branch, that's up to you. After that, I don't mind waiting for you to finish the site's new UI so that I can modify my code again to adapt it to the new UI.

**Comment by derklaro** [comment]
Maybe I'm a bit late to the party, but I'm wondering: wdyt about removing the signal indication from the info box and displaying it using the train marker ring color instead? For example: vmax - green ring, speed restriction - yellow ring, stop - red ring (instead of the blue ring used for all trains rn):
image

**Comment by Julian-Louis** [comment]
> So far, I think the UI is pretty good. Unfortunately, I can't reduce the space between Signal Status and Signal Speed too much, otherwise the image would be too small.

I think the image is currently too big ?: 
image
What do you think ?

**Comment by Over441** [comment]
Yes, I can reduce it.

**Comment by Over441** [comment]
Here's how it looks.

When the signal is too far away :

image

And here is the normal case: 

image


I'm pretty happy with the result!
Let me know if I need to alter anything @Julian-Louis

**Review by Julian-Louis — APPROVED** [review]

**Comment by Julian-Louis** [comment]
Thank you for your contribution !

**Comment by Over441** [comment]
You're welcome, it makes me happy!

**Pull request merged**
