### PR TITLE
show train length/weight, add missing train thumbnails

### PR DESCRIPTION
**Pull request by derklaro**
I've taken the time to copy all the train detail information from the train depot into a json file, which I now used to display the train length and weight information in the train popup. Additionally while at it, I've also updated the train thumbnails, which should now include a thumbnail for every locomotive or emu that is playable in the game (they are the same images, but mine are more compressed than the old ones). The name that is reported by the API is now part of the json file, which allows to remove the method that mapped api name -> image path.

This also includes a full rewrite of the train text component (I know this makes it harder to review, sorry, but it was easier than just throwing in even more stuff :/). Please note that the train length and weight are sometimes off the actual value shown in game, and sometimes perfectly accurate. I'm not sure why this is the case, but it's probably due to some additional parameter that comes into the calculation that is just not available to me. The difference is not much (a few meters and ~20t at max), but it is there. As an indication it should be enough imo.

image

### CODE REVIEW

**Comment by SparklesReal** [comment]
image
Other units: x2
I enjoyed being able to see all types. Is there any specific reason for this changes or is it just preference?

**Comment by derklaro** [comment]
Well, ultimately it always comes down to preference 😜 In this case I was thinking about 3 things: 1. the other locomotives don't do anything anyway, so why display them (conclusion was: some people might want to drive trains with multiple locomotives explicitly, so leave it in), 2. Displaying all types looked confusing and increased the size of the box for no apparent reason, so it again came down to just showing the count, and 3. the types of the other locomotives can be seen by looking at the pictures which will show all types that are in the trainset, which (at least for me) is enough to know which types are in the set. Hope that explains it well enough.

Another thing I just thought about while looking at the pictures: would it be better to display the "other unit"/"wagons" info before length / weight, and should I remove the "train" prefix from the length info? ("Train Length / Weight" -> "Length / Weight")

**Comment by SparklesReal** [comment]
I mean that is fair. I agree with the part that the other unit and wagons should be displayed over the weight info. This might also be just me but the '~' seems a bit useless as you already get that it is rounded and it looks a bit weird. Would be nice to get some other peoples inputs.

**Review by Julian-Louis — APPROVED** [review]
Thank you for your contribution !

**Pull request merged**
